### ISSUE TITLE
求word文档

### ISSUE THREAD

**Issue by tianqiang-PENG** [derekwin/Software-for-calculating-chromatic-aberration#1]
您好，您做的这个色差检测系统太棒了，正好与我现在的课题有很多相似之处，看了代码有不懂得地方，跪求文档，希望能借助文档好好理解一下，非常感谢!!

**Comment by derekwin** [comment]
不好意思 ，现在才看到您的issue。由于年代太久了，当时的项目文档丢失了=，=。所以没法提供了，sorry。
